### ISSUE TITLE
update_secondary_metadata_from_mlwh doesn't update permissions

### ISSUE THREAD

**Issue by kjsanger** [wtsi-npg/npg-irods-python#317]
`update_secondary_metadata_from_mlwh` should update "metadata" in the broad sense, to include data access permissions as well as iRODS annotation. It doesn't do this, meaning that if a study has had its ACL changed, that won't be reflected in the result.

**Comment by mgcam** [comment]
Closed via https://github.com/wtsi-npg/npg-irods-python/pull/318
